import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Toaster } from "@/components/ui/sonner"
import { cn } from "@/lib/utils";

export const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Dashboard Majors",
  description: "Generated by create next app",
  authors: [
    {
      name: "Marcelo Bracet",
      url: "marcelo.bracet1@gmail.com",
    },
    {
      name: "João Vinícius Vitral",
      url: "joaoviniciusvitral@hotmail.com",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="pt-br">
        <body
          className={cn(
            "min-h-screen font-sans antialiased bg-[#060B26]",
            fontSans.variable
          )}
        >
        {children}
        <Toaster/>
        </body>
      </html>
  );
}
